### ISSUE TITLE
What does localAddr and localPort mean?

### ISSUE THREAD

**Issue by zhaoyi0113** [parro-it/open-ssh-tunnel#12]
I am able to use this library to create a ssh tunnel. But what I don't understand is the `localAddr and localPort`. In the example from the README, it is set as below value. Where is the machine for IP address `192.168.1.2`? Is it a separate host or a different network interface on client host? 

```
    localAddr: 27018,
    localPort: '192.168.1.2'
```

**Comment by parro-it** [comment]
> In the example from the README, it is set as below value. Where is the machine for IP address 192.168.1.2? Is it a separate host or a different network interface on client host?

It is a different network interface on client host. You have to provide it if you want other machines in client lan to use the tunnel you create.

**Comment by zhaoyi0113** [comment]
Ok, thank for your explanation.

**Comment by parro-it** [comment]
You're welcome :smile:
